sudo: required
language: go
go: 1.8
services:
    - docker

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    - provider: script
      script: make login && make push
      on:
          branch: master
