sudo: required
language: go
go: 1.8
services:
    - docker

script:
    - go get -v ./...
    - wget https://raw.githubusercontent.com/toddmotto/public-apis/master/json/entries.min.json
    - make

deploy:
    - provider: script
      script: make login && make push
      on:
          branch: master
